### ISSUE TITLE
otter.ai-api is missing from npmjs.org

### ISSUE THREAD

**Issue by Stvad** [omerdn1/otter.ai-api#6]
It does not seem to be possible to install the package from npm anymore :(

**Comment by Stvad** [comment]
used this for an Alfred WF: https://github.com/Stvad/alfred-otter/

for now installing an updated version from my fork. lmk if you plan to re-publish this at some point/up for accepting PRs

**Comment by omerdn1** [comment]
@Stvad The package has been republished. I'm planning to fix the issue you raised in #7 in an elegant way. I'll update the repository in the upcoming days.

Thank you for bringing this to my attention!
Closing this.
